vpx_enc_fuzzer: add missing break statements
Fixes unintended fall through, resulting in limited resolution coverage,
and the related `-Wimplicit-fallthrough`:

```
examples/vpx_enc_fuzzer.cc:187:5: error: unannotated fall-through
between switch labels [-Werror,-Wimplicit-fallthrough]
  187 |     case 1: cfg.g_w = 1; cfg.g_h = 48;
      |     ^
examples/vpx_enc_fuzzer.cc:187:5: note: insert '[[fallthrough]];' to
silence this warning
  187 |     case 1: cfg.g_w = 1; cfg.g_h = 48;
      |     ^
      |     [[fallthrough]];
examples/vpx_enc_fuzzer.cc:187:5: note: insert 'break;' to avoid
fall-through
  187 |     case 1: cfg.g_w = 1; cfg.g_h = 48;
      |     ^
      |     break;
```

Change-Id: Id9fd5e06de8dfd99a34a57aeedfcf7be103096f4